name: Build Debug APK

on:
  workflow_dispatch:   # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: List files in current directory
        run: |
          echo "Current directory: $(pwd)"
          ls -la
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev
          pip install --user --upgrade Cython==0.29.33 virtualenv
          pip install --user --upgrade buildozer
      - name: Build with buildozer
        run: |
          export PATH=$PATH:~/.local/bin
          buildozer -v android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: bin/*.apk
